"""Subagents: pure functions over tools + workspace — no LLM required for demo."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .mcp_tools import CodebaseTools


@dataclass
class Plan:
    goal: str
    touch_files: list[str]
    required_api: list[str]
    notes: str = ""


class PlannerAgent:
    """Maps a structured goal dict into a Plan (deterministic)."""

    def plan(self, goal: str, spec: dict[str, Any]) -> Plan:
        touch = list(spec.get("touch_files") or ["agent_out/module.py"])
        api = list(spec.get("required_api") or ["run"])
        return Plan(goal=goal, touch_files=touch, required_api=api, notes=spec.get("notes", ""))


class CoderAgent:
    """Writes minimal Python implementing required_api stubs or a specified body."""

    def __init__(self, tools: CodebaseTools):
        self.tools = tools

    def implement(self, plan: Plan, body: dict[str, str] | None = None) -> list[dict[str, Any]]:
        body = body or {}
        results = []
        for rel in plan.touch_files:
            if rel in body:
                src = body[rel]
            else:
                lines = [
                    '"""Generated by CoderAgent — replace stubs for production."""',
                    "from __future__ import annotations",
                    "",
                ]
                for name in plan.required_api:
                    lines += [
                        f"def {name}(*args, **kwargs):",
                        f'    """Stub for {name} — goal: {plan.goal[:60]}"""',
                        "    return {\"ok\": True, \"fn\": %r}" % name,
                        "",
                    ]
                src = "\n".join(lines)
            results.append(self.tools.call("fs_write", {"path": rel, "content": src}).to_dict())
        return results


class VerifierAgent:
    def __init__(self, tools: CodebaseTools):
        self.tools = tools

    def check_compile(self, paths: list[str]) -> list[dict[str, Any]]:
        out = []
        for p in paths:
            out.append(self.tools.call("py_compile_check", {"path": p}).to_dict())
        return out


class CriticAgent:
    """Null-arm thinker: propose abstain reasons if gates weak."""

    def review(self, gate_details: list[str]) -> str | None:
        bad = [d for d in gate_details if d and d != "ok"]
        if bad:
            return "critic: residual failures — " + "; ".join(bad[:3])
        return None
